Parital convert to graphic shaders, vertex shader
Vertex shader kind of wired in; it's the dummy one from
https://www.saschawillems.de/?page_id=2122
that generates a single full screen triangle.

Problem with:
thread 'main' panicked at 'raypipe: VertexFragmentStagesMismatch(ElementsCountMismatch { self_elements: 0, other_elements: 1 })', libcore/result.rs:945:5